# Generated by Django 4.2.7 on 2023-11-10 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='gambar',
            field=models.ImageField(upload_to='movie/images/'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toko',
            name='telpon',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='min 8 digit', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
