# Generated by Django 4.2.7 on 2023-11-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasar', '0002_alter_barang_gambar_alter_barang_keterangan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='tersdia',
            field=models.CharField(choices=[('1', 'Tersedia'), ('0', 'Tidak Tersedia')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
