# Generated by Django 4.2.7 on 2023-11-10 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasar', '0003_barang_tersdia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='tersdia',
        ),
        migrations.AddField(
            model_name='barang',
            name='tersedia',
            field=models.CharField(choices=[('1', 'Tersedia'), ('0', 'Tidak tersedia')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item_total', models.IntegerField(default=0)),
                ('makanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasar.barang')),
            ],
        ),
    ]
